version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "manager"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - GolangAndPostgreSql
  golang:
    container_name: golang
    working_dir: /go/src/neoway
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOSTNAME=host.docker.internal
      - DB_PORT_NUMBER=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=manager
      - DB_NAME=neoway
    networks:
      - GolangAndPostgreSql
networks: 
  GolangAndPostgreSql:
    driver: bridge